export const LOGIN_ROUTE = '/login'
export const CHAT_ROUTE = '/chat'
export const MESSENGER_ROUTE ='/mes'
export const HOME_ROUTE = '/'
export const REGISTERED_CHAT_ROUTE = '/chat/registered'
export const INCOGNITO_CHAT_ROUTE = '/chat/incognito'
